### ISSUE TITLE
scrollTop would cause reflow

### ISSUE THREAD

**Issue by noppanit** [fusioneng/Co-Authors-Plus-Roles#17]
https://github.com/goldenapples/Co-Authors-Plus-Roles/blob/master/includes/js/coauthors.js#L341

This is just an idea that I want to throw it out there. I realise that there's no quick fix for this but it would be good to consider this in the future. scrollTop would cause reflow of the whole page which is bad in terms of performance. If we can think of a way not to use this value it would be nice.

**Comment by goldenapples** [comment]
Does just reading the scrollTop value trigger reflow? I thought it was just a wrapper around `window.pageYOffset`.

https://github.com/jquery/jquery/blob/74ae5444832b2fb966768a97281d2ad8c088bc58/src/offset.js#L177-179

**Comment by noppanit** [comment]
Ah sorry that's from jQuery. I thought that's from DOM property.

**Comment by goldenapples** [comment]
Closing this issue. This JS file probably needs to be rewritten for performance as well as responsiveness (what happens when the viewport is too short to contain the entire modal, for example), but I'll address that separately.
