### ISSUE TITLE
All translatable strings should have the proper textdomain

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/Co-Authors-Plus-Roles#5]
Seeing some missing like `__( 'Contributing Author' )`.

I thought I also saw one with `co-authors-plus` as the textdomain, instead of the roles plugin.

**Comment by goldenapples** [comment]
I used `co-authors-plus` when I was using strings that were already internationalized in Co-Authors Plus, thinking that would save translators some work. 

Thinking about it, I can see that is confusing. I'll give everything a consistent textdomain.

**Comment by goldenapples** [comment]
Fixed in #20.
